version: "3"
services:
  grpc-server:
    container_name: grpc-server
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: grpcpapp:v0.1
    ports: 
    - "9090:9090"
    command: ["node", "server.js"]

  grpc-client:
    container_name: grpc-client
    image: grpcpapp:v0.1
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    ports:
      - "4001:4001"
    command: ["node", "client.js"]
  
  grpc-frontend:
    container_name: grpc-frontend
    image: grpcpapp:v0.1
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    command: ["npm", "start"]
  